# pip install numpy

In [25]:
# pip install numpy


In [26]:
import numpy as np

## creating an array using numpy

In [27]:
name = np.array(["kamal","hamid","talha","ali"])
name

array(['kamal', 'hamid', 'talha', 'ali'], dtype='<U5')

In [28]:
sur_name =np.array(["khan","khan","akbar","khan"])
sur_name

array(['khan', 'khan', 'akbar', 'khan'], dtype='<U5')

In [29]:
type(name)

numpy.ndarray

In [30]:
len(name)

4

In [31]:
sur_name[0:]

array(['khan', 'khan', 'akbar', 'khan'], dtype='<U5')

In [32]:
name[1]

'hamid'

In [33]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [38]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
np.arange(3,33,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [45]:
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [43]:
#specify your data type
np.ones(50, dtype=np.int64)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [44]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array function

In [47]:
a = np.array([23,4,5,2,3,34,2.5,432,657,55,6,86,88,698,656])
a

array([ 23. ,   4. ,   5. ,   2. ,   3. ,  34. ,   2.5, 432. , 657. ,
        55. ,   6. ,  86. ,  88. , 698. , 656. ])

In [49]:
a.sort()
a

array([  2. ,   2.5,   3. ,   4. ,   5. ,   6. ,  23. ,  34. ,  55. ,
        86. ,  88. , 432. , 656. , 657. , 698. ])

In [50]:
b = np.array([10.2,3.4,3.2,5,6,3,1,2])
b

array([10.2,  3.4,  3.2,  5. ,  6. ,  3. ,  1. ,  2. ])

In [54]:
c =np.concatenate((a,b))

In [55]:
c.sort()
c

array([  1. ,   2. ,   2. ,   2.5,   3. ,   3. ,   3.2,   3.4,   4. ,
         5. ,   5. ,   6. ,   6. ,  10.2,  23. ,  34. ,  55. ,  86. ,
        88. , 432. , 656. , 657. , 698. ])

## 2-D array

In [56]:
a = np.array([[43,23,4,5],[1,6,4,34,32]])
a 

C:\Users\Talha\AppData\Local\Temp\ipykernel_3272\2034433783.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[43,23,4,5],[1,6,4,34,32]])


array([list([43, 23, 4, 5]), list([1, 6, 4, 34, 32])], dtype=object)

In [82]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [57]:
b = np.array([[73,53,6,54],[51,64,43,4,3]])
b

C:\Users\Talha\AppData\Local\Temp\ipykernel_3272\546043670.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[73,53,6,54],[51,64,43,4,3]])


array([list([73, 53, 6, 54]), list([51, 64, 43, 4, 3])], dtype=object)

In [59]:
np.concatenate((a,b),axis=0)

array([list([43, 23, 4, 5]), list([1, 6, 4, 34, 32]),
       list([73, 53, 6, 54]), list([51, 64, 43, 4, 3])], dtype=object)

In [78]:
f = ([[[123,23,1,3],[21,43,5,4]],[[21,34,6,4],[34,5,4,3]],[[34,5,43,2],[32,5,64,3]]])
f

[[[123, 23, 1, 3], [21, 43, 5, 4]],
 [[21, 34, 6, 4], [34, 5, 4, 3]],
 [[34, 5, 43, 2], [32, 5, 64, 3]]]

In [81]:
f.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [77]:
b.ndim

1

In [76]:
a.size

AttributeError: 'list' object has no attribute 'size'

In [75]:
a.shape

AttributeError: 'list' object has no attribute 'shape'